### ISSUE TITLE
Implementación de Diseño Responsivo en la Segunda Página

### ISSUE THREAD

**Issue by Scar269** [Scar269/Ontas-bebe#10]
Como equipo de desarrollo es necesario la implementación de un diseño responsivo en la tercera página del proyecto para asegurar que la página se vea y funcione correctamente en dispositivos de diferentes tamaños de pantalla. Esto incluye el uso de media queries para ajustar el diseño y los estilos de la página según sea necesario.

Definir Puntos de Ruptura (Breakpoints)
- [x]  Identificar los puntos de ruptura clave (por ejemplo, para dispositivos móviles, tablets y pantallas de escritorio).

Aplicar Media Queries
- [x]  Crear media queries para los puntos de ruptura definidos.
- [x]  Ajustar el tamaño y la disposición de la imagen circular, el título, el párrafo y el botón para diferentes tamaños de pantalla.
- [x]  Ajustar los márgenes y el relleno de los elementos para asegurar una apariencia adecuada en todas las resoluciones.
- [x]  Asegurar que el contenido se ajuste adecuadamente dentro de la tarjeta (si se decide usar una).

Probar en Diferentes Dispositivos y Tamaños de Pantalla
- [x]  Probar la página en varios dispositivos (móvil, tablet, escritorio) y en varios tamaños de pantalla para asegurar que el diseño responsivo funcione correctamente.
- [x]  Ajustar los estilos según sea necesario basado en los resultados de las pruebas.

*No olvidar dejar el espacio al final de cada archivo

**Comment by TilinMamarre69** [comment]
He finalizado el responsivo de la segunda página, procederé a realizar un Pull Request para su aprobación y adición a Main.
