### ISSUE TITLE
Implemetación de API Formspree para enviar correo al obtener ubicación

### ISSUE THREAD

**Issue by Scar269** [Scar269/Ontas-bebe#12]
Como equipo de desarrollo es necesario enviar un correo al obtener la ubicación del usuario utilizando la API de Formspree.

- [x] Se añade un EventListener para el evento click en el botón con el ID goToReset.
- [x] Se crean variables name, email y un mensaje estático que se van a enviar en la solicitud.
- [x] Se utilizaría fetch para enviar una solicitud POST al servidor.
- [x] Se incluye el encabezado Content-Type: application/json.
- [x] Se convierte el objeto data a formato JSON usando JSON.stringify.
- [x] Se agrega una promesa que convierte la respuesta a formato JSON.
- [x] Se añade lógica para redirigir a return.html si la respuesta es exitosa (responseData.ok).
- [x] Se añade una alerta en caso de que haya un problema al enviar los datos.
- [x] Se capturan errores usando .catch y se agrega una alerta en caso de error.

**Comment by TilinMamarre69** [comment]
Hasta el momento no se ha podido solucionar el problema del que hemos discutido. Proseguiremos con el Issue asignado el día de ayer.
