### ISSUE TITLE
Vinculación de Apis: Formspree, Geolocation

### ISSUE THREAD

**Issue by Scar269** [Scar269/Ontas-bebe#23]
Como equipo de desarrollo es necesario permitir el envío de correos electrónicos con información de geolocalización personalizada mejora la experiencia del usuario al recibir datos relevantes y específicos basados en su ubicación. Por lo que se deberá realizar la integración de dos APIs: Formspree y Geolocation:

Obtención de Información de Geolocation:
- [x] Implementación de una solicitud a la API de Geolocation para obtener información basada en la ubicación del usuario.

Preparación de Datos para el Correo:
- [x] Procesamiento de la información obtenida de la API de Geolocation para formatearla adecuadamente.
- Ejemplo de datos obtenidos: ciudad, país, coordenadas, etc.

Envío de Correo mediante Formspree:
- [x] Configuración de la solicitud POST a Formspree con los datos obtenidos de la API de Geolocation.
- [x] Uso de fetch para enviar la solicitud a Formspree.

Manejo de Respuestas y Errores:
- [x] Manejo de la respuesta de Formspree para confirmar que el correo se ha enviado correctamente.

*Dejar un espacio al final de cada archivo, si esto ya se ha hecho favor de ignorar esta parte

**Comment by darkukore** [comment]
![image](https://github.com/user-attachments/assets/3679632e-421c-4f8a-908b-4204fbcc1614)

Adjunto evidencia sobre la prueba de vinculación de las API's Formspree y Geolocation.
@TilinMamarre69 favor de responder este comentario con el resultado.

**Comment by TilinMamarre69** [comment]
He realizado la prueba de la vinculación, todo parece funcionar con éxito, felicidades equipo.
![image](https://github.com/user-attachments/assets/a86362d8-4bab-463c-b0e1-285dec27ee77)
