### ISSUE TITLE
Corrección de detalles estilo css - 2da pagina

### ISSUE THREAD

**Issue by Scar269** [Scar269/Ontas-bebe#29]
Como equipo de desarrollo es necesario añadir un margen a la tarjeta, pues asegura que haya suficiente espacio entre los elementos, lo que facilita la lectura y la navegación

- [x] Se añadió una propiedad margin en el archivo CSS correspondiente o en la etiqueta style en línea de la tarjeta.
- [x] El margen se aplicó a los cuatro lados de la tarjeta para asegurar un espaciado uniforme.

**Comment by TilinMamarre69** [comment]
Se hizo el pull request con la corrección y procedió a mergearse.
