### ISSUE TITLE
Implementación de Diseño Responsivo en la Primera Página

### ISSUE THREAD

**Issue by Scar269** [Scar269/Ontas-bebe#9]
Como equipo de desarrollo es necesario la implementación de un diseño responsivo en la segunda página del proyecto para asegurar que la página se vea y funcione correctamente en dispositivos de diferentes tamaños de pantalla. Esto incluye el uso de media queries para ajustar el diseño y los estilos de la página según sea necesario.

Definir Puntos de Ruptura (Breakpoints)
- [x]  Identificar los puntos de ruptura clave (por ejemplo, para dispositivos móviles, tablets y pantallas de escritorio).

Aplicar Media Queries
- [x]  Crear media queries para los puntos de ruptura definidos.
- [x]  Ajustar el tamaño y la disposición de la tarjeta para diferentes tamaños de pantalla.
- [x]  Ajustar los márgenes y el relleno de los elementos para asegurar una apariencia adecuada en todas las resoluciones.
- [x]  Asegurar que el botón se mantenga legible y accesible en todos los dispositivos.

Probar en Diferentes Dispositivos y Tamaños de Pantalla
- [x]  Probar la página en varios dispositivos (móvil, tablet, escritorio) y en varios tamaños de pantalla para asegurar que el diseño responsivo funcione correctamente.
- [x]  Ajustar los estilos según sea necesario basado en los resultados de las pruebas.

*No olvidar dejar el espacio al final de cada archivo

**Comment by TilinMamarre69** [comment]
Se agregarán los diseños posterior a la entrega del día de hoy y, si es posible, terminar con la parte que nos corresponde.

**Comment by TilinMamarre69** [comment]
Se ha concluido con el diseño responsivo de la primera página, se creó el Pull Request para su revisión.
